#!/bin/bash -l

#SBATCH --job-name=stringtie_merge
#SBATCH -A beagle
#SBATCH -t 120:00:00
#SBATCH -n 40
#SBATCH --output="stringtie_merge.out"
#SBATCH --error="stringtie_merge.err"


module purge
module load biocontainers
module load stringtie/2.2.1


cd /scratch/bell/nbackens/daphnia_RNAseq/02_degs/assembled_transcripts

# merge all transcripts from all samples + reference annotation
stringtie --merge -p 40 \
-G /scratch/bell/nbackens/daphnia_RNAseq/reference/genomic.gff \
-o stringtie_all_merged.gtf mergelist.txt

